name: app-ci-cd pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'msa/apigateway/**'
      - 'msa/member/**'
      - 'msa/ordering/**'
      - 'msa/product/**'
      - 'msa/frontend/**'

env:
  ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
  GITOPS_REPO: ${{ vars.GITOPS_REPO }}
  GITOPS_BRANCH: ${{ vars.GITOPS_BRANCH }}

jobs:
  ci-cd-pipeline:
    runs-on: ubuntu-latest   # GitHub가 제공하는 Ubuntu 가상머신에서 실행

    permissions:
      id-token: write
      contents: read
    
    steps:
      # GitHub 코드 체크아웃
      - name: checkout github
        # actions/checkout@v4
        # 현재 GitHub 저장소 코드를 runner(ubuntu 서버)에 내려받는 공식 액션
        # 이 단계 없으면 docker build할 소스 코드가 없음
        uses: actions/checkout@v4

      # 현재 커밋 SHA 앞 7자리로 IMAGE_TAG 생성
      - name: Create IMAGE_TAG with GITHUB_SHA
        id: image_tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      # AWS 인증 (OIDC)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Assume 할 IAM Role ARN
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}

          # 인증 대상 AWS 리전
          aws-region: ${{ vars.AWS_REGION }}

      # ECR 로그인
      - name: Login to ECR
        # aws-actions/amazon-ecr-login@v2
        # → Docker가 AWS ECR에 push할 수 있도록 로그인 처리
        uses: aws-actions/amazon-ecr-login@v2
      
      # dorny/paths-filter@v3
      # push에서 변경된 파일 목록을 분석 지정한 경로에 변경이 있으면 true/false 자동 생성
      # changes.outputs.member 같은 값으로 접근 가능
      # push 이벤트일 때만 변경된 서비스 감지
      - name: Detect changed services
        if: github.event_name == 'push'
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            gateway:
              - 'msa/apigateway/**'
            member:
              - 'msa/member/**'
            ordering:
              - 'msa/ordering/**'
            product:
              - 'msa/product/**'
            frontend:
              - 'msa/frontend/**'

      # push 이벤트에서 변경 없으면 종료
      - name: stop if no service changed
        # 모든 서비스가 false일 경우 실행
        # 불필요한 docker build 방지
        if: |
          github.event_name == 'push' &&
          steps.changes.outputs.gateway != 'true' &&
          steps.changes.outputs.member != 'true' &&
          steps.changes.outputs.ordering != 'true' &&
          steps.changes.outputs.product != 'true' &&
          steps.changes.outputs.frontend != 'true'
        run: |
          echo "No service directory changed. Skip build."
          exit 0

      # GitOps manifest 수정이 필요한 push 이벤트일 때만 yq 설치
      - name: Install yq
        if: github.event_name == 'push'
        run: |
          sudo wget -O /usr/local/bin/yq \
            https://github.com/mikefarah/yq/releases/download/v4.44.2/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          yq --version

      # workflow_dispatch: 전체 이미지 push
      # push: 변경된 서비스만 이미지 push

      # APIGateway build/push
      - name: Build and push apigateway image
        if: github.event_name == 'workflow_dispatch' || steps.changes.outputs.gateway == 'true'
        env:
          REPOSITORY: apigateway
          DOCKERFILE_PATH: ./msa/apigateway/Dockerfile
          BUILD_CONTEXT: ./msa/apigateway
        run: |
          docker build \
            -t ${ECR_REGISTRY}/${REPOSITORY}:${IMAGE_TAG} \
            -f ${DOCKERFILE_PATH} ${BUILD_CONTEXT}

          docker push ${ECR_REGISTRY}/${REPOSITORY}:${IMAGE_TAG}

      # Member build/push
      - name: Build and push member image
        if: github.event_name == 'workflow_dispatch' || steps.changes.outputs.member == 'true'
        env:
          REPOSITORY: member-service
          DOCKERFILE_PATH: ./msa/member/Dockerfile
          BUILD_CONTEXT: ./msa/member
        run: |
          docker build \
            -t ${ECR_REGISTRY}/${REPOSITORY}:${IMAGE_TAG} \
            -f ${DOCKERFILE_PATH} ${BUILD_CONTEXT}

          docker push ${ECR_REGISTRY}/${REPOSITORY}:${IMAGE_TAG}

      # Ordering build/push
      - name: Build and push ordering image
        if: github.event_name == 'workflow_dispatch' || steps.changes.outputs.ordering == 'true'
        env:
          REPOSITORY: ordering-service
          DOCKERFILE_PATH: ./msa/ordering/Dockerfile
          BUILD_CONTEXT: ./msa/ordering
        run: |
          docker build \
            -t ${ECR_REGISTRY}/${REPOSITORY}:${IMAGE_TAG} \
            -f ${DOCKERFILE_PATH} ${BUILD_CONTEXT}

          docker push ${ECR_REGISTRY}/${REPOSITORY}:${IMAGE_TAG}

      # Product build/push
      - name: Build and push product image
        if: github.event_name == 'workflow_dispatch' || steps.changes.outputs.product == 'true'
        env:
          REPOSITORY: product-service
          DOCKERFILE_PATH: ./msa/product/Dockerfile
          BUILD_CONTEXT: ./msa/product
        run: |
          docker build \
            -t ${ECR_REGISTRY}/${REPOSITORY}:${IMAGE_TAG} \
            -f ${DOCKERFILE_PATH} ${BUILD_CONTEXT}

          docker push ${ECR_REGISTRY}/${REPOSITORY}:${IMAGE_TAG}

      # Frontend build/push
      - name: Build and push frontend image
        if: github.event_name == 'workflow_dispatch' || steps.changes.outputs.frontend == 'true'
        env:
          REPOSITORY: frontend-service
          DOCKERFILE_PATH: ./msa/frontend/Dockerfile
          BUILD_CONTEXT: ./msa/frontend
        run: |
          docker build \
            -t ${ECR_REGISTRY}/${REPOSITORY}:${IMAGE_TAG} \
            -f ${DOCKERFILE_PATH} ${BUILD_CONTEXT}

          docker push ${ECR_REGISTRY}/${REPOSITORY}:${IMAGE_TAG}

      # 아래부터는 push 이벤트일 때만 수행
      # GitOps repo checkout
      - name: Checkout GitOps repo
        if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GITOPS_REPO }}
          ref: ${{ env.GITOPS_BRANCH }}
          token: ${{ secrets.GH_PAT }}
          path: gitops

      # APIGateway manifest tag 수정
      - name: Update apigateway manifest
        if: github.event_name == 'push' && steps.changes.outputs.gateway == 'true'
        env:
          FULL_IMAGE: ${{ env.ECR_REGISTRY }}/apigateway:${{ env.IMAGE_TAG }}
          FILE_PATH: gitops/apps/apigateway/depl.yaml
        run: |
          yq -i '
            .spec.template.spec.containers[].image = strenv(FULL_IMAGE)
          ' "${FILE_PATH}"

      # Member manifest tag 수정
      - name: Update member manifest
        if: github.event_name == 'push' && steps.changes.outputs.member == 'true'
        env:
          FULL_IMAGE: ${{ env.ECR_REGISTRY }}/member-service:${{ env.IMAGE_TAG }}
          FILE_PATH: gitops/apps/member/depl.yaml
        run: |
          yq -i '
            .spec.template.spec.containers[].image = strenv(FULL_IMAGE)
          ' "${FILE_PATH}"

      # Ordering manifest tag 수정
      - name: Update ordering manifest
        if: github.event_name == 'push' && steps.changes.outputs.ordering == 'true'
        env:
          FULL_IMAGE: ${{ env.ECR_REGISTRY }}/ordering-service:${{ env.IMAGE_TAG }}
          FILE_PATH: gitops/apps/ordering/depl.yaml
        run: |
          yq -i '
            .spec.template.spec.containers[].image = strenv(FULL_IMAGE)
          ' "${FILE_PATH}"

      # Product manifest tag 수정
      - name: Update product manifest
        if: github.event_name == 'push' && steps.changes.outputs.product == 'true'
        env:
          FULL_IMAGE: ${{ env.ECR_REGISTRY }}/product-service:${{ env.IMAGE_TAG }}
          FILE_PATH: gitops/apps/product/depl.yaml
        run: |
          yq -i '
            .spec.template.spec.containers[].image = strenv(FULL_IMAGE)
          ' "${FILE_PATH}"

      # Frontend manifest tag 수정
      - name: Update frontend manifest
        if: github.event_name == 'push' && steps.changes.outputs.frontend == 'true'
        env:
          FULL_IMAGE: ${{ env.ECR_REGISTRY }}/frontend-service:${{ env.IMAGE_TAG }}
          FILE_PATH: gitops/apps/frontend/depl.yaml
        run: |
          yq -i '
            .spec.template.spec.containers[].image = strenv(FULL_IMAGE)
          ' "${FILE_PATH}"

      # Git 설정
      - name: Configure git identity
        if: github.event_name == 'push'
        working-directory: gitops
        run: |
          git config user.name "${{ vars.GITOPS_COMMIT_USER_NAME }}"
          git config user.email "${{ vars.GITOPS_COMMIT_USER_EMAIL }}"

      # 변경사항 commit/push
      - name: Commit and push manifest changes
        if: github.event_name == 'push'
        working-directory: gitops
        run: |
          git add apps/apigateway/depl.yaml \
                  apps/member/depl.yaml \
                  apps/ordering/depl.yaml \
                  apps/product/depl.yaml \
                  apps/frontend/depl.yaml

          if git diff --cached --quiet; then
            echo "No manifest changes to commit."
            exit 0
          fi

          git commit -m "chore: update image tags to ${IMAGE_TAG}"
          git push origin "${GITOPS_BRANCH}"
